### ISSUE TITLE
Alternate backends with numba or pythran?

### ISSUE THREAD

**Issue by u55** [Jomiri/pyfiberamp#6] opened 2018-11-12 20:16 UTC
Unfortunately, I have not been able to try the pre-compiled C++ bindings, even on Windows, because I have older CPUs that lack AVX2 instruction support. Since polishing and maintaining the (presumably handwritten) C++ source code sounds like a bit of a hassle for you, I wonder if you are interested in supporting another alternate backend with numba or pythran? 

The `Dynamic example 1 - Pulsed amplification` example takes 25 minutes to run on my machine with the pure python backend. However, by rewriting a few inner-loop functions in python and adding numba decorators or pythran type annotations and compiling to C++11 (see below), I have been able to get the example to run in 76 seconds (20x speedup) with numba and 54 seconds (28x speedup) with pythran.

Here are the modified inner-loop functions:
```python
import numpy as np
from numba import njit

#pythran export dPdZ(float[][], float[][], float[][], float[][], float[][], float, int, int, bool)
@njit
def dPdZ(P_hat, N2, a_g_per_Nt, a_l, g_m_h_v_dv_per_Nt, dz, num_ion_populations, n_channels, add):
    """Modifies `P_hat` in-place."""
    out = np.zeros_like(P_hat)
    for i in range(num_ion_populations):
        start = i * n_channels
        for j in range(out.shape[0]):
            for k in range(out.shape[1]):
                out[j, k] += P_hat[j, k] * (a_g_per_Nt[start+j, k] * N2[i, k] - a_l[start+j, k]) + (g_m_h_v_dv_per_Nt[start+j, k] * N2[i, k])
    if add:
        P_hat[:, :] = P_hat + (dz * out)
    else:
        P_hat[:, :] = P_hat - (dz * out)

#pythran export dNdT(float[][], float[][], float[][], float[][], float, float, int, int)
@njit
def dNdT(N2, P, a_per_h_v_pi_r2, a_g_per_h_v_pi_r2_Nt, A, dt, num_ion_populations, n_channels):
    """Modifies `N2` in-place."""
    out = np.empty_like(N2)
    for i in range(num_ion_populations):
        start = i * n_channels
        tmp = np.zeros(out.shape[1], dtype=out.dtype)
        for k in range(out.shape[1]):
            for j in range(n_channels):
                tmp[k] += P[j, k] * (a_per_h_v_pi_r2[start+j, k] - a_g_per_h_v_pi_r2_Nt[start+j, k] * N2[i, k])
            out[i, k] = tmp[k] - A * N2[i, k]
    N2[:, :] = N2 + (dt * out)

#pythran export shift_against_propagation_direction_to_from(float[][], float[][], int)
@njit
def shift_against_propagation_direction_to_from(P_hat_backward, P_hat_forward, n_forward):
    """Modifies `P_hat_backward` in-place."""
    P_hat_backward[:n_forward, :-1] = P_hat_forward[:n_forward, 1:]
    P_hat_backward[n_forward:, 1:] = P_hat_forward[n_forward:, :-1]

#pythran export shift_to_propagation_direction_to_from(float[][], float[][], int)
@njit
def shift_to_propagation_direction_to_from(P_hat_forward, P, n_forward):
    """Modifies `P_hat_foreward` in-place."""
    P_hat_forward[:n_forward, 1:] = P[:n_forward, :-1]
    P_hat_forward[n_forward:, :-1] = P[n_forward:, 1:]

#pythran export min_clamp(float[][], float)
@njit
def min_clamp(arr, min_value):
    """Modifies `arr` in-place."""
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i, j] < min_value:
                arr[i, j] = min_value

#pythran export apply_input(float[][], float[][], int, int)
@njit
def apply_input(P, P_in_out, idx_iteration, n_forward):
    """Modifies `P` in-place."""
    P[:n_forward, 0] = P_in_out[:n_forward, idx_iteration]
    P[n_forward:, -1] = P_in_out[n_forward:, idx_iteration]

#pythran export apply_output(float[][], float[][], int, int)
@njit
def apply_output(P_in_out, P_hat_forward, idx_iteration, n_forward):
    """Modifies `P_in_out` in-place."""
    P_in_out[:n_forward, idx_iteration] = P_hat_forward[:n_forward, -1]
    P_in_out[n_forward:, idx_iteration] = P_hat_forward[n_forward:, 0]

#pythran export apply_reflection(float[][], int[], int[], float[], int)
@njit
def apply_reflection(P, source_idx, target_idx, R, n_forward):
    """Modifies `P` in-place."""
    for _source_idx, _target_idx, _R in zip(source_idx, target_idx, R):
        if _source_idx < n_forward:
            P[_target_idx, -1] += _R * P[_source_idx, -2]
        else:
            P[_target_idx, 0] += _R * P[_source_idx, 1]

#pythran export new_P(float[][], float[][], float[][])
@njit
def new_P(P, P_hat_forward, P_hat_backward):
    """Modifies `P` in-place."""
    P[:, :] = P_hat_forward + 0.5 * (P - P_hat_backward)
```
Using pythran is as simple as commenting out the numba import and `@njit` decorators, then compiling to a native extension module with:
```
pythran filename.py
```

I am guessing that these 9 python functions are much smaller and easier to maintain than handwritten C++. I can submit a pull request, if you are interested. Otherwise, this post might serve as a useful guide to other users.

**Comment by Jomiri** [comment] 2018-11-13 18:34
Impressive results! I'd definitely be interested in supporting another backend if numba and pythran can achieve such sizeable speedups. It would also be a shame to leave your code here where few would find it given the amount of work you must have done to make all those modifications. 

Which one of the two compiler tools would be a better fit for pyfiberamp in your opinion? Pythran seems to output faster code but my impression is that numba would be easier to install is more mature overall. Can the pythran extension be generated setup.py, for example?

I had to check the execution times of example 1 on my own computer for comparison. Using the current python backend, the simulation ran in 13 min 39 s and switching to the C++ backend reduced the time to 4.0 s (~200x speedup). Assuming that the pythran code would run in ~30 s on my computer, it would come pretty close to the C++ backend.

**Comment by u55** [comment] 2018-11-13 21:02
Yes, I was able to get setup.py to optionally compile the pythran extension module if pythran is installed.

I would also guess that numba is easier to use on Windows with anaconda, but on linux either pythran or numba is equally easy to install and use.

**Comment by u55** [comment] 2018-11-13 21:03
Sorry, I meant to hit "comment" not "close and comment".

**Comment by u55** [comment] 2018-11-13 21:13
If and when you get around to polishing and releasing your C++ code, then pythran has no advantage and appears to be slower, based on your 200x speed benchmark. But numba would still be useful to users (especially Windows users) who don't have a C++ compiler and have a different operating-system/CPU-architecture/python-version than the prebuilt binaries you make.

**Comment by xmhk** [comment] 2018-11-13 21:36
Hi, 
I just wanted to mention that this patch works fine for me. I tested on Arch Linux, Python 3.7. For both numba and pythran, the dynamic examples give reasonable results in <1 min (Intel Core i5).

Nice work, u55!

Regards, Christoph

**Comment by Jomiri** [comment] 2018-11-14 17:23
Nice work indeed and thanks for the feedback Christoph! I'll do some work on the new backends, most importantly I need to add them to the test cases, and hope to merge them into master within the week. I'll leave this issue open until then.

**Comment by Jomiri** [comment] 2018-11-24 17:08
I've now merged the new backends into master. For some reason, the pythran extension would not compile on my Windows computer but I trust that it works on Linux. The numba backend works fine and passes the tests. I refactored the switch methods used to select the backend but did not modify the actual numerical code yet. Thanks again for this contribution!

**Closed by Jomiri** 2018-11-24 17:08 UTC

**Comment by xmhk** [comment] 2018-11-24 21:53
Hi, I just built the the updated master branch package with setup.py and both Pythran and numba backends compile and work as intended (on Linux). 

Best, Christoph
