### ISSUE TITLE
Dynamic Simulation - C++ backend could not be loaded on system with AVX2 support

### ISSUE THREAD

**Issue by langesimmons** [Jomiri/pyfiberamp#2] opened 2018-06-18 19:38 UTC
When running a dynamic simulation, the warning about the C++ backend is given and defaults to the Python solver. I looked around for the pyfiberamp.dynamic.fiber_simulation_pybindings file that is imported for the DynamicSolverCPP, but could not find it. I am running Windows 10 on an [i5-8250U](https://ark.intel.com/products/124967/Intel-Core-i5-8250U-Processor-6M-Cache-up-to-3_40-GHz).
Thanks for any help!

**Comment by Jomiri** [comment] 2018-06-19 15:28
Thanks for the heads-up! 

The problem is that setup.py does not copy the compiled extension file to the install location in site-packages. I'll try to fix this as soon as possible. Meanwhile, there are two workarounds: 1) You can manually copy the "fiber_simulation_pybindings.cp36-win_amd64.pyd" file from the download folder to the pyfiberamp/dynamic subfolder in site-packages. 2) You can remove the current installation (just delete the PyFiberAmp folder in site-packages) and then reinstall using developer installation with the command "python setup.py develop". This creates a link in site-packages without actually copying any files. Just don't delete the originally downloaded files in that case. If you're using the Anaconda distribution, the site-packages folder is typically located in C:\Users\[USERNAME]\Anaconda3\Lib.

The funny thing is that I had this same problem myself and specifically checked on one computer that I had it fixed before pushing the new version to GitHub. However, I was able to reproduce the problem on a different computer today so there's still definitely something wrong.

**Comment by langesimmons** [comment] 2018-06-19 16:54
Thanks for the help. I tried the develop installation, but that didn't work. When I went to try the first way, I couldn't find the .pyd in the repository, in my download or on GitHub. Maybe that's the issue?

**Comment by Jomiri** [comment] 2018-06-19 17:15
The installation should work now. One of the regex conditions in .gitignore was actually capturing the pyd file and that's why it wasn't showing on GitHub. I have no idea how I could've missed that. Anyway, I'll close this issue after testing the installation tomorrow on a different computer and if you get it working, too. Thanks a lot for the feedback!

**Comment by langesimmons** [comment] 2018-06-19 18:06
Thanks, it works perfectly now! Ran setup.py install with no issues. Love the project!

**Comment by Jomiri** [comment] 2018-06-20 14:22
Great! I got it working for me as well, so I'm closing this issue now.

**Closed by Jomiri** 2018-06-20 14:22 UTC
